import { Saree } from "@/types";

export const seedSarees: Saree[] = [
  {
    id: "1",
    name: "Royal Red Banarasi Silk Saree",
    price: 8500,
    fabric: "Banarasi",
    color: "Red",
    occasion: "Wedding",
    images: ["/sarees/saree-1.jpg", "/sarees/saree-1-detail.jpg"],
    featured: true,
    available: true,
    blousePiece: true,
    length: "6.3 meters",
    careInstructions: "Dry clean only. Store in a cool, dry place. Avoid direct sunlight.",
    description: "Elegant red Banarasi silk saree with intricate golden zari work. Perfect for weddings and special occasions. Features traditional motifs and fine craftsmanship that showcase the rich heritage of Banaras weaving.",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Elegant Blue Silk Saree",
    price: 6200,
    fabric: "Silk",
    color: "Blue",
    occasion: "Party",
    images: ["/sarees/saree-2.jpg"],
    featured: true,
    available: true,
    blousePiece: true,
    length: "5.5 meters",
    careInstructions: "Dry clean only. Iron on low heat.",
    description: "Beautiful blue silk saree perfect for parties and evening events. The lustrous silk fabric drapes elegantly and features delicate embellishments that catch the light beautifully.",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    name: "Traditional Green Kanjivaram",
    price: 12000,
    fabric: "Kanjivaram",
    color: "Green",
    occasion: "Wedding",
    images: ["/sarees/saree-3.jpg"],
    featured: true,
    available: true,
    blousePiece: true,
    length: "6.3 meters",
    careInstructions: "Dry clean only. Store with camphor to prevent insects.",
    description: "Authentic Kanjivaram silk saree in rich green with traditional temple border. This handwoven masterpiece features pure zari work and represents generations of South Indian weaving tradition.",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "4",
    name: "Pastel Pink Cotton Saree",
    price: 3200,
    fabric: "Cotton",
    color: "Pink",
    occasion: "Daily",
    images: ["/sarees/saree-4.jpg"],
    featured: false,
    available: true,
    blousePiece: true,
    length: "5.5 meters",
    careInstructions: "Machine washable. Use mild detergent.",
    description: "Comfortable cotton saree for daily wear. Breathable fabric perfect for hot weather, featuring subtle prints and easy-to-maintain material that's ideal for everyday elegance.",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "5",
    name: "Golden Georgette Party Saree",
    price: 4500,
    fabric: "Georgette",
    color: "Gold",
    occasion: "Party",
    images: ["/sarees/saree-5.jpg"],
    featured: false,
    available: true,
    blousePiece: true,
    length: "5.5 meters",
    careInstructions: "Dry clean only. Handle with care.",
    description: "Shimmering georgette saree with sequin work. The lightweight fabric drapes beautifully and the golden hue adds a touch of glamour to any party or celebration.",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "6",
    name: "Purple Chiffon Designer Saree",
    price: 5800,
    fabric: "Chiffon",
    color: "Purple",
    occasion: "Festive",
    images: ["/sarees/saree-6.jpg"],
    featured: false,
    available: false,
    blousePiece: true,
    length: "5.5 meters",
    careInstructions: "Dry clean only. Do not wring.",
    description: "Designer chiffon saree with modern prints. Contemporary design meets traditional elegance in this statement piece that's perfect for festive occasions.",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "7",
    name: "Maroon Chanderi Silk Saree",
    price: 7200,
    fabric: "Chanderi",
    color: "Maroon",
    occasion: "Formal",
    images: ["/sarees/saree-7.jpg"],
    featured: false,
    available: true,
    blousePiece: true,
    length: "6.3 meters",
    careInstructions: "Dry clean only. Iron on low heat with cloth.",
    description: "Luxurious Chanderi silk saree in deep maroon. Known for its sheer texture and lightweight feel, this saree combines comfort with sophistication.",
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "8",
    name: "Cream Cotton Silk Daily Wear",
    price: 3800,
    fabric: "Cotton",
    color: "Cream",
    occasion: "Daily",
    images: ["/sarees/saree-8.jpg"],
    featured: false,
    available: true,
    blousePiece: true,
    length: "5.5 meters",
    careInstructions: "Hand wash or machine wash gentle cycle.",
    description: "Elegant cream cotton silk saree perfect for daily wear. Comfortable yet sophisticated, ideal for office wear or casual occasions.",
    createdAt: new Date("2024-03-05"),
  },
];
